# Image de base
FROM
# Qui est le responsable de cette image
MAINTAINER

# Install elasticsearch
# 1. Récupérer elasticsearch
# 2. L'extraire à l'endroit souhaité
# 3. Supprimer l'archive récupérer (pour gagner de la place)
# Try 2 methods : multiple lines, one-line
RUN

# Declare volume
VOLUME

# Installer un plugin elasticsearch, par example
# - http://mobz.github.io/elasticsearch-head/
# - https://github.com/uberVU/elasticsearch-river-github
RUN

# Ajouter votre configuration elasticsearch
ADD

# Expose les ports souhaités (9200, 9300)
EXPOSE

# Le dossier de travail
WORKDIR

# La commande par défaut
CMD
