# Image de base
FROM
# Qui est le responsable de cette image
MAINTAINER

# Install elasticsearch
# 1. Récupérer elasticsearch : https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.2.tar.gz
# 2. L'extraire à l'endroit souhaité : tar xvzf
# 3. Supprimer l'archive récupérer (pour gagner de la place)
RUN

# Declare volume
VOLUME ["/data"]

# Installer un plugin elasticsearch, par example
# - http://mobz.github.io/elasticsearch-head/
# - https://github.com/uberVU/elasticsearch-river-github
RUN

# Ajouter votre configuration elasticsearch
ADD

# Expose les ports souhaités (9200, 9300)
EXPOSE

# Le dossier de travail
WORKDIR /data

# La commande par défaut
CMD
